//Activos 
//export const ASSETS = 'BTC;ETH;USDT;XRP;BUSD;DOGE;ADA;DOT;DAI;WBTC;LTC;LINK;ETC;XLM;XMR'
//export const ASSETS = 'BTC;ETH;BNB;USDT;XRP;ADA;SOL;DOGE;DOT;AVAX;LINK;LTC;UNI;SHIB;BCH';
//export const ASSETS = 'BTC;ETH;BNB;XRP;ADA;SOL;DOT;DOGE;LTC;UNI;LINK;BCH;XLM;ATOM;FIL';
export const ASSETS = 'BTC;ETH;XRP;ADA;DOT;DOGE;LTC;LINK;BCH;XLM;ATOM;FIL;XMR;BUSD;TRX';
